dev:
    steps:
        - name: build
          command: go build -o epit_15 ./cmd/main.go
          duration: true
        - name: build16
          envs:
            - EXEC_PATH=$GO_EXEC_PATH
            - $GO16_NAME=epic_16
          command: $EXEC_PATH/go1.16beta1 build -o $GO16_NAME ./cmd/main.go
          duration: true
        - name: test
          command: go test ./...
        - name: checking
          command: ls -la


release:
  steps:
    - name: tag
      command: git tag $GOPROJECT_TAG
prod:
    env:
        - TEST_APP=foobar
    command: "ls -la"