dev:
    steps:
        - name: envs
          command: go env
        - name: build
          command: go build -o epit ./cmd/main.go
          duration: true
        - name: test
          command: go test ./...

prod:
    env:
        - TEST_APP=foobar
    command: "ls -la"